- name: create folder
  file:
    path: "{{ item }}"
    state: directory
  become: yes
  with_items:
  - /var/bronner/etc/nginx/conf.d
  - /var/bronner/etc/nginx/conf.d/services
  - /var/bronner/www_root
  - /var/bronner/www_root/letsencrypt

- name: config server
  copy:
    src: nginx.conf
    dest: /var/bronner/etc/nginx/nginx.conf
  become: yes

- name: http config
  template:
    src: http-root.conf
    dest: /var/bronner/etc/nginx/conf.d/http-root.conf
  become: yes

- name: create a container
  docker_container:
    name: reverse-proxy
    image: nginx:alpine
    state: started
    restart: yes
    purge_networks: yes
    networks:
    - name: bronner
    published_ports:
    - 0.0.0.0:80:80
    - 0.0.0.0:443:443
    volumes:
    - /var/bronner/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /var/bronner/etc/nginx/conf.d:/etc/nginx/conf.d
    - /var/bronner/etc/nginx/passwds:/etc/nginx/passwds
    - /var/bronner/etc/certbot:/etc/certbot
    - /var/bronner/www_root:/var/www
    - /var/bronner/trajan-static:/static
    env:
      NGINX_HOST: "{{ host_name }}"
      NGINX_PORT: 80
  become: yes
